### ISSUE TITLE
Change ntPublish option of DogLogOptions to BooleanSupplier

### ISSUE THREAD

**Issue by Daniel1464** [jonahsnider/doglog#57]
I'm personally fine with implementing this myself, but I want to see how to best implement this:

- I'm thinking that if this change happens, the default value for DogLogOptions.ntPublish should be ```() -> !DriverStation.isFMSAttached()```. I feel like most teams will use this option anyways, so it's a good default to set.
-  If not, we can just have a BooleanSupplier that returns false.

**Comment by jonahsnider** [comment]
Hey! So, I see where you're coming from with this suggestion, and I do agree that it'd be nice if the default behavior used `DriverStation.isFMSAttached()`. My main concern is that from a performance standpoint, switching from reading a `boolean` field to calling a `BooleanSupplier` would make things a teensy bit slower across the board. Specifically, this would mean that every time a value is logged, that supplier would need to be polled to see whether NT logging should be used.

Here's a few ideas I have for getting similar behavior with what DogLog supports now:
- What we do on 581 is just have a static field `IS_DEVELOPMENT` in our robot config class.
  - At comps, we set this to `false`, which disables NT publishing ([example](https://github.com/team581/2024-offseason-bot/blob/89e35f3f9be559acfec4791ca1bf8ccb7ee2ebf9/src/main/java/frc/robot/Robot.java#L62-L63))
- DIY this behavior by manually updating the settings when `DriverStation.isFMSAttached()` changes
  - Can add a small piece of code like this to `robotPeriodic()` or something
    ```java
    var options = DogLog.getOptions();
    var fmsAttached = DriverStation.isFMSAttached();
    if (options.ntPublish() == fmsAttached) {
      DogLog.setOptions(options.withNtPublish(!fmsAttached));
    }
    ```

Do either of these seem like they'd work for your use case?

**Comment by Daniel1464** [comment]
Yeah you might be right on the performance standpoint; my thought was that it would be nice to have NT logging turn on and off automatically so you don't have to re-deploy code.
This isn't a problem with our specific usecase(we already use triggers for enabling/disabling network tables logging) and moreso setting a default that 99% of teams won't switch away from(which is nice).

**Comment by jonahsnider** [comment]
Yeah, definitely I would prefer to have this behavior by default, but with the rio's processing limitations I'm very cautious on introducing any kind of extra potential overhead. I will keep this idea in the back of my head though, and if there's a good way to implement it I'll for sure do that. Thanks for the suggestion!
